[project]
name = "sparkiceberg-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.1",
    "jupyterlab>=4.4.9",
    "mkdocs>=1.6.1",
    "pyspark==3.5.3",
]
